server:
  port: 9094
spring:
  application:
    name: ribbon-eureka-provider
#单点eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@140.143.81.236:9090/eureka/
  instance:
    preferIpAddress: true




