#服务端口
server:
  port: 9090

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:123@${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka
  security:
    user:
      name: user
      password: 123
