server:
  port: 9081
spring:
  application:
    name: hystrix-terbine
#单点eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@140.143.81.236:9090/eureka/
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream




